### ISSUE TITLE
Derived datasets

### ISSUE THREAD

**Issue by dnoesgaard** [andrewhywong/SDM-GeoAttribution#2]
Hey, thanks for using derived dataset records the GBIF data. I noticed that the records didn't have any information about contributing datasets, so I took the liberty of matching up the GBIF ids to their parent datasets and adding the relevant metadata to the datasets. This ensures that data publishers are credited within the GBIF citation system.

**Comment by andrewhywong** [comment]
> Hey, thanks for using derived dataset records the GBIF data. I noticed that the records didn't have any information about contributing datasets, so I took the liberty of matching up the GBIF ids to their parent datasets and adding the relevant metadata to the datasets. This ensures that data publishers are credited within the GBIF citation system.

Hey - thanks a lot for helping on this! Sorry that I didn't check on the derived sources. Would it be possible for you to kindly provide methods you used to match up the GBIF IDs or other dataset keys, in our case that the occurrence data were originally retrieved from `occ_search()` function? For future data I'll use `occ_download()` to prepare for better citation form. 

Thank you!

**Comment by dnoesgaard** [comment]
Hey, to match GBIF occurrence IDs with parent datasets, you can either use the GBIF API:

`https://api.gbif.org/v1/occurrence/<occurrence id>`

and get the value from `datasetKey`. Example: `https://api.gbif.org/v1/occurrence/3112345088` returns:

```
{
"key": 3112345088,
"datasetKey": "50c9509d-22c7-4a22-a47d-8c48425ef4a7"
```

In this case, however, for several hundreds of thousands of records, this will take forever. So you're better of reaching out to us and we can help you through some parallel processing magic ;)

`occ_download()` is the safe route because a DOI is assigned at the time of download so you don't have to worry about it. But if you filter data extensively and end up with a reduced dataset, you might still want to produce a new citable record only referring to the records used. In this case, just make sure to to always retain the `datasetKey` column, and you're good and you can use those as the metadata for a derived dataset.

Make sense?

**Comment by andrewhywong** [comment]
> Hey, to match GBIF occurrence IDs with parent datasets, you can either use the GBIF API:
> 
> `https://api.gbif.org/v1/occurrence/<occurrence id>`
> 
> and get the value from `datasetKey`. Example: `https://api.gbif.org/v1/occurrence/3112345088` returns:
> 
> ```
> {
> "key": 3112345088,
> "datasetKey": "50c9509d-22c7-4a22-a47d-8c48425ef4a7"
> ```
> 
> In this case, however, for several hundreds of thousands of records, this will take forever. So you're better of reaching out to us and we can help you through some parallel processing magic ;)
> 
> `occ_download()` is the safe route because a DOI is assigned at the time of download so you don't have to worry about it. But if you filter data extensively and end up with a reduced dataset, you might still want to produce a new citable record only referring to the records used. In this case, just make sure to to always retain the `datasetKey` column, and you're good and you can use those as the metadata for a derived dataset.
> 
> Make sense?

These really help! Thanks for the information!
